# Generated by Django 3.1 on 2020-09-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settler', '0003_auto_20200921_1937'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(currency__regex='^[A-Z]{3}$'), name='accoount_currency_regex_alpha3'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(currency__regex='^[A-Z]{3}$'), name='transaction_currency_regex_alpha3'),
        ),
    ]
