# Generated by Django 3.1 on 2020-09-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settler', '0004_auto_20200921_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
