# Generated by Django 3.1 on 2020-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.BinaryField(),
        ),
    ]
