# Generated by Django 3.1 on 2020-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fex', '0002_auto_20200930_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scheme',
            field=models.CharField(choices=[('eu.sepa.sct', 'eu.sepa.sct')], default='eu.sepa.sct', max_length=70),
            preserve_default=False,
        ),
    ]
