# Generated by Django 3.1.2 on 2020-10-02 22:24

from django.db import migrations, models
import django_countries.fields
import localflavor.generic.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SepaRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('scheme', models.CharField(choices=[('eu.sepa.sct', 'eu.sepa.sct'), ('eu.sepa.sctinst', 'eu.sepa.sctinst'), ('eu.sepa.sddcore', 'eu.sepa.sddcore'), ('eu.sepa.sddb2b', 'eu.sepa.sddb2b')], max_length=70)),
                ('external_key', models.CharField(max_length=16)),
                ('bic', localflavor.generic.models.BICField(max_length=11)),
                ('psp_name', models.CharField(max_length=140)),
                ('psp_city', models.CharField(max_length=35)),
                ('psp_country', django_countries.fields.CountryField(max_length=2)),
                ('reachable_via', models.CharField(blank=True, max_length=4)),
                ('reachablility_type', models.CharField(choices=[('direct', 'Direct Participant'), ('indirect', 'Indirect Participant')], max_length=16)),
                ('intermediary_bic', localflavor.generic.models.BICField(blank=True, max_length=11)),
                ('preferred_route', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(null=True)),
            ],
        ),
    ]
