# Generated by Django 3.1.2 on 2020-10-02 23:07

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separoute',
            name='intermediary_bic',
            field=localflavor.generic.models.BICField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='separoute',
            name='valid_from',
            field=models.DateField(null=True),
        ),
    ]
