# Generated by Django 3.1.2 on 2020-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separoute',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='separoute',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
