# Generated by Django 3.1.2 on 2020-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_auto_20201002_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separoute',
            name='reachablility_type',
            field=models.CharField(choices=[('direct', 'Direct Participant'), ('indirect', 'Indirect Participant'), ('unknown', 'Unknown')], max_length=16),
        ),
    ]
