# Generated by Django 3.1.2 on 2020-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_auto_20201003_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separoute',
            name='scheme',
            field=models.CharField(choices=[('eu.sepa.sct', 'EU SEPA SCT'), ('eu.sepa.sctinst', 'EU SEPA SCT Inst'), ('eu.sepa.sddcore', 'EU SEPA SDD CORE'), ('eu.sepa.sddb2b', 'EU SEPA SDD B2B'), ('eu.sepa.scc', 'EU SEPA Card Clearing')], max_length=70),
        ),
    ]
