# Generated by Django 3.1.2 on 2020-10-04 22:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_auto_20201003_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separoute',
            options={'verbose_name': 'SEPA route'},
        ),
        migrations.AlterField(
            model_name='separoute',
            name='external_key',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='separoute',
            name='psp_city',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='separoute',
            name='psp_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='separoute',
            name='reachable_via',
            field=models.CharField(blank=True, choices=[('EBAS', 'STEP2 PE-ACH (Belgium)'), ('STPA', 'FIXME STPA'), ('CECB', 'CEC (Belgium)'), ('DBSC', 'SEPA-Clearer (Germany)'), ('PBSD', 'Sumclearing (Denmark)'), ('IBPA', 'Iberpay (Spain)'), ('STET', 'STET (France)'), ('SCTI', 'ICBPI/BI-COMP (Italy)'), ('EQNS', 'Equens (Netherlands)'), ('KIRP', 'Euro Elixir (Poland)'), ('CTRL', 'CENTROlink (Lithuania)'), ('TIPS', 'TIPS (Germany)'), ('CSIA', 'CS.I (Austria)'), ('DIAS', 'DIAS (Greece)'), ('BSRA', 'BISERA7-EUR (Bulgaria)')], max_length=4),
        ),
    ]
